### ISSUE TITLE
multilabel/multiclass

### ISSUE THREAD

**Issue by vtrokhymenko** [PyTorchLightning/lightning-transformers#141]
did the task `text classification` support multiclass and/or multilabel classification?

**Comment by SeanNaren** [comment]
Thanks for your issue!

Yes it does! Some of the pre-made HF datasets are multi-class: https://huggingface.co/datasets/emotion#default-1

I'll make the docs clearer to reflect this

**Comment by vtrokhymenko** [comment]
good
so, at the field `label` i should point some labels separated `,`

**Comment by SeanNaren** [comment]
> good
> so, at the field `label` i can point some labels separated `,`

The field `label` actually refers to the label for that specific sample, i.e `cat` `dog` etc. So at once, the model has to identify one label from a selection of X, if that makes sense!

IF the choices change per sample, have a look at our Multiple Choice Task: https://lightning-transformers.readthedocs.io/en/latest/tasks/nlp/multiple_choice.html

**Comment by vtrokhymenko** [comment]
i want to watch more examples of your lib

for now, i have `text` and `labels` like "mask", "tesla", "spacex" ..
for this task i can use multiple choice or no? if yes, how i can enter manual the fields i need

**Comment by SeanNaren** [comment]
So for each sample of text, like so:

```json
{
    "text": "Hi I am elon musk",
    "label": "tesla"
},
{
    "text": "Send a rocket into space",
    "label": "spacex"

```

Related to #155 I'll clear up the format of data so it's clearer to people!

**Comment by RaedShabbir** [comment]
Hello, 

To confirm, you currently support multi-class but not multi-label? Can't find any examples in the docs regarding multi-label.

**Comment by RaedShabbir** [comment]
@SeanNaren any word on this?

**Comment by SeanNaren** [comment]
hey @RaedShabbir! by multi-label could you give an example? Chances are it is supported, the docs just need clarification :)

**Comment by RaedShabbir** [comment]
Thanks for getting back to me @SeanNaren, 

I mean one hot encodings as the label vector, so the data would look similar to https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/data

In other words
each text can have from 0 up to N labels, where N is the total number of labels.
