### ISSUE TITLE
Tutorial link is dead

### ISSUE THREAD

**Issue by zippeurfou** [PyTorchLightning/lightning-transformers#145]
## 📚 Documentation
The top nav has `Tutorials` that is a dead link to https://lightning-transformers.readthedocs.io/quickstart.html
<img width="1786" alt="Screen Shot 2021-04-22 at 10 32 53 AM" src="https://user-images.githubusercontent.com/4520383/115732618-2187e080-a356-11eb-8871-dadb826dae70.png">

**Comment by carmocca** [comment]
cc: @edenlightning
