### ISSUE TITLE
Create the equivalent of boring model for issues template for bugs

### ISSUE THREAD

**Issue by zippeurfou** [PyTorchLightning/lightning-transformers#156]
## 🚀 Feature
We should have the equivalent of boringmodel  in PL for issues template for bugs

### Motivation

Just make our life easier to report and fix :) 

### Pitch
I reported an issue with this https://colab.research.google.com/drive/1uamw6SNaOr_4ch24JNxAj2yfgLUKfJqO?usp=sharing I think it just makes it easier overall to understand the issue.
I'd suggest changing the logo, adding a better way to create the different kind of data files.

**Comment by SeanNaren** [comment]
Thanks Marc!

We'll get there, we do have a simple BoringTransformerModel and DataModule for testing: https://github.com/PyTorchLightning/lightning-transformers/blob/master/tests/core/boring_model.py exposing this to the user would be great.

I think we can have non-hydra boring model template script and a hydra CLI command to run to replicate issues.
