### ISSUE TITLE
Loading and saving model files and checkpoints

### ISSUE THREAD

**Issue by astoeckl** [PyTorchLightning/lightning-transformers#167]
## 📚 Documentation
Some questions on saving and loading model files:

How can I save a .ckpt file after each epoch of training?
How can I save a model file after training as PyTorch model file (.bin)?

How can I restart training from a saved .ckpt file?

**Comment by SeanNaren** [comment]
Thanks for your issue and apologies on the late response! We'll add all this into the documentation to make it clear.

By default we save every epoch as per Lightning: https://pytorch-lightning.readthedocs.io/en/latest/common/weights_loading.html#weights-loading

I'm unsure what you mean by a PyTorch model file, could you give more details?

Restarting from a saved ckpt seems to not be supported currently, will look into integration for this!

**Comment by astoeckl** [comment]
I want to upload a fine-tuned model file to the Hugging face model hub. Therefore I need the PyTorch model file and not only the ckpt.

**Comment by SeanNaren** [comment]
ah I see! so you want the output from `model.save_pretrained`. This hasn't been added yet but I can make this an option! to do so right now you might be able to load the model and save the internal model i.e for text classification:

```python
task = TextClassificationTransformer.load_from_checkpoint('model.pt')
task.model.save_pretrained('huggingfacemodel.pt')
task.tokenizer.save_pretrained('huggingfacetokenizer.pt')
```
