### ISSUE TITLE
Missing Compressed-Dictionary dependency

### ISSUE THREAD

**Issue by pedrocolon93** [PyTorchLightning/lightning-transformers#217]
## 🐛 Bug

For some reason, I always have to install compressed-dictionary for this library to work.

### To Reproduce

```
pip install transformers-lightning
from transformers_lightning.schedulers import LinearSchedulerWithWarmup
```
The error is that the library is missing.
#### Code sample
See above
### Expected behavior

That the pip install has the dependency
### Environment

python 3.9+ 
torch 1.9+
transformers - latest

**Comment by mathemusician** [comment]
Hi! I'm confused. This is the `lightning-transformers` repository, not the `transformers-lightning` repository. You might actually want to raise your issue here: [https://github.com/iKernels/transformers-lightning](https://github.com/iKernels/transformers-lightning)

**Comment by Borda** [comment]
closing this issue as it unrelated to this project.

**Comment by pedrocolon93** [comment]
Whoops! I completely inverted the thing! Sorry!
