### ISSUE TITLE
Add DataClass Hydra Support

### ISSUE THREAD

**Issue by SeanNaren** [PyTorchLightning/lightning-transformers#40]
Related #37 

The final piece is to add automatic defaults + type checking for dataclasses.

Two options:

* Via the ConfigStore: https://hydra.cc/docs/next/tutorials/structured_config/schema/ which would need to store all configs that we'd like to type check/duck-type via Hydra. The object remains a DictConfig (duck-typing)
* Carlos Idea: provide a `_name_` within the config to automatically convert to a specific data-class, go through the tree recursively

Choice 1 is closer to Hydra, Choice 2 is better because we actually pass data-classes around.

**Comment by omry** [comment]
OmegaConf 2.1 can now convert the config to real dataclasses:

https://omegaconf.readthedocs.io/en/latest/usage.html#omegaconf-to-object
