### ISSUE TITLE
Integrate SQuAD v2 metric

### ISSUE THREAD

**Issue by SeanNaren** [PyTorchLightning/lightning-transformers#60]
## 🚀 Feature

Currently there is no way to calculate the SQuAD metric. This is due to some complications in the metric aggregation. A wip branch can be seen here: https://github.com/PyTorchLightning/lightning-transformers/tree/wip-qa-metric

Continue integration of a QA metric!

**Comment by benschreiber** [comment]
What is the current status of this?

**Comment by SeanNaren** [comment]
There was a very rudimentary implementation at https://github.com/PyTorchLightning/lightning-transformers/tree/wip-qa-metric that does not currently work.

The main issue comes from the metric relying on outputs collected from the entire validation/test step which is quite an aggregation. Not sure I'll have time to work on this right now, but happy if someone wants to take a stab making a SQuAD metric for [torchmetrics](https://github.com/PyTorchLightning/metrics) :)

**Comment by benschreiber** [comment]
Could the squad metric already in `🤗Datasets` be used? https://github.com/huggingface/datasets/tree/1.6.2/metrics/squad
Or is there a way I could hack it to use that, for my own purposes?
